-- ============================================================
-- Seed the 18 AI categories
-- ============================================================

insert into public.categories (slug, title, subtitle, icon, gradient, glow_color, border_color, text_accent, bg_card, enabled, show_sidebar, show_homepage, premium, order_index, tags)
values
  ('generador-video',   'Generador de Video',   'Crea videos profesionales con IA en segundos',     'Video',     'from-pink-500 via-rose-500 to-red-600',         'shadow-pink-500/25',     'border-pink-500/20',     'text-pink-400',    'from-pink-500/10 to-rose-500/5',     true, true, true, false, 1,  array['IA','Video','Texto a Video']),
  ('editor-video',      'Editor de Video',      'Edición profesional con inteligencia artificial',  'Film',      'from-violet-500 via-purple-500 to-fuchsia-600', 'shadow-violet-500/25',   'border-violet-500/20',   'text-violet-400',  'from-violet-500/10 to-purple-500/5', true, true, true, false, 2,  array['Edición','Timeline','Efectos']),
  ('automatizaciones',  'Automatizaciones',     'Flujos de trabajo inteligentes que trabajan por ti','Zap',       'from-yellow-400 via-orange-500 to-amber-600',   'shadow-yellow-500/25',   'border-yellow-500/20',   'text-yellow-400',  'from-yellow-500/10 to-orange-500/5', true, true, true, false, 3,  array['CRM','Email','WhatsApp','IA']),
  ('generador-voz',     'Generador de Voz',     'Voces IA ultra-realistas en más de 30 idiomas',    'Mic',       'from-cyan-400 via-blue-500 to-indigo-600',      'shadow-cyan-500/25',     'border-cyan-500/20',     'text-cyan-400',    'from-cyan-500/10 to-blue-500/5',     true, true, true, false, 4,  array['Voz IA','Multilingüe','Clonación']),
  ('generador-imagen',  'Generador de Imagen',  'Crea imágenes impresionantes con prompts de texto','Image',     'from-emerald-400 via-teal-500 to-green-600',    'shadow-emerald-500/25',  'border-emerald-500/20',  'text-emerald-400', 'from-emerald-500/10 to-teal-500/5',  true, true, true, false, 5,  array['DALL-E','Stable Diffusion','Upscale']),
  ('cursos-prompt',     'Cursos de Prompt',     'Domina la ingeniería de prompts para IA',          'BookOpen',  'from-blue-400 via-indigo-500 to-purple-600',    'shadow-blue-500/25',     'border-blue-500/20',     'text-blue-400',    'from-blue-500/10 to-indigo-500/5',   true, true, true, true,  6,  array['Prompts','ChatGPT','Academia']),
  ('venta-cursos',      'Venta de Cursos',      'Tu academia online con pagos y membresías',        'ShoppingBag','from-orange-400 via-red-500 to-rose-600',      'shadow-orange-500/25',   'border-orange-500/20',   'text-orange-400',  'from-orange-500/10 to-red-500/5',    true, true, true, true,  7,  array['LMS','Membresías','Stripe']),
  ('venta-paginas',     'Venta de Páginas',     'Templates, funnels y sitios web premium',          'Layout',    'from-fuchsia-500 via-pink-500 to-purple-600',   'shadow-fuchsia-500/25',  'border-fuchsia-500/20',  'text-fuchsia-400', 'from-fuchsia-500/10 to-pink-500/5',  true, true, true, false, 8,  array['Templates','Funnels','Landing Pages']),
  ('afiliados',         'Afiliados',            'Genera ingresos recurrentes con comisiones',       'Users',     'from-green-400 via-emerald-500 to-teal-600',    'shadow-green-500/25',    'border-green-500/20',    'text-green-400',   'from-green-500/10 to-emerald-500/5', true, true, true, false, 9,  array['Comisiones','Referidos','Pagos']),
  ('marca-blanca',      'Marca Blanca',         'Tu propio SaaS con tu marca y dominio',            'Globe',     'from-slate-400 via-gray-500 to-zinc-600',       'shadow-slate-500/25',    'border-slate-500/20',    'text-slate-300',   'from-slate-500/10 to-gray-500/5',    true, true, true, true,  10, array['White Label','DNS','SaaS Reseller']),
  ('ai-chatbots',       'AI Chatbots',          'Bots inteligentes para WhatsApp, Instagram y web', 'Bot',       'from-sky-400 via-cyan-500 to-teal-600',         'shadow-sky-500/25',      'border-sky-500/20',      'text-sky-400',     'from-sky-500/10 to-teal-500/5',      true, true, true, false, 11, array['Chatbot','WhatsApp','Instagram','GPT-4']),
  ('funnels',           'Funnels Inteligentes', 'Embudos de venta con IA y plantillas',             'Filter',    'from-rose-400 via-pink-500 to-fuchsia-600',     'shadow-rose-500/25',     'border-rose-500/20',     'text-rose-400',    'from-rose-500/10 to-fuchsia-500/5',  true, true, true, false, 12, array['Funnels','Conversión','Templates']),
  ('email-marketing',   'Email Marketing AI',   'Campañas, autoresponders y copywriting con IA',    'Mail',      'from-amber-400 via-yellow-500 to-orange-600',   'shadow-amber-500/25',    'border-amber-500/20',    'text-amber-400',   'from-amber-500/10 to-orange-500/5',  true, true, true, false, 13, array['Email','Autoresponders','IA Copy']),
  ('social-scheduler',  'Social Media Scheduler','Programa y automatiza TikTok, Instagram, X',      'CalendarClock','from-violet-400 via-purple-500 to-indigo-600','shadow-violet-500/25', 'border-violet-500/20',   'text-violet-400',  'from-violet-500/10 to-indigo-500/5', true, true, true, false, 14, array['TikTok','Instagram','Programador']),
  ('crm',               'CRM Inteligente',      'Pipeline, leads y automatizaciones todo en uno',   'Briefcase', 'from-teal-400 via-emerald-500 to-green-600',    'shadow-teal-500/25',     'border-teal-500/20',     'text-teal-400',    'from-teal-500/10 to-green-500/5',    true, true, true, false, 15, array['CRM','Pipeline','Leads']),
  ('agencia-ia',        'Agencia IA',           'Herramientas pro para agencias y consultores',     'Sparkles',  'from-purple-400 via-fuchsia-500 to-pink-600',   'shadow-purple-500/25',   'border-purple-500/20',   'text-purple-400',  'from-purple-500/10 to-pink-500/5',   true, true, true, true,  16, array['Agencia','Clientes','Reporting']),
  ('plantillas-premium','Plantillas Premium',   'Canva, ads, social y branding kits listos',        'Palette',   'from-pink-400 via-rose-500 to-red-600',         'shadow-pink-500/25',     'border-pink-500/20',     'text-pink-400',    'from-pink-500/10 to-red-500/5',      true, true, true, false, 17, array['Canva','Ads','Templates']),
  ('streaming-podcast', 'Streaming & Podcast',  'Studio profesional para creators y podcasters',    'Radio',     'from-red-400 via-rose-500 to-pink-600',         'shadow-red-500/25',      'border-red-500/20',      'text-red-400',     'from-red-500/10 to-pink-500/5',      true, true, true, true,  18, array['Streaming','Podcast','Audio'])
on conflict (slug) do nothing;
